Repository PICNIC-DEV/wazoo-backend, pull requests merged in 2024-08, with the labels that each got.

#21 Feature/wazoo 9
  src/main/java/wazoo/controller/SurveyController.java
  src/main/java/wazoo/controller/UserController.java
  src/main/java/wazoo/dto/SurveyQuestionDto.java
  src/main/java/wazoo/dto/SurveyRequestDto.java
  src/main/java/wazoo/service/SurveyService.java
  src/main/java/wazoo/service/UserService.java
  src/main/resources/questions.json
Labels: refactoring

#24 [Feature/wazoo 11] guide api 구현
  build.gradle
  src/main/java/wazoo/config/AwsConfig.java
  src/main/java/wazoo/controller/GuideController.java
  src/main/java/wazoo/dto/GuideDto.java
  src/main/java/wazoo/entity/Guide.java
  src/main/java/wazoo/repository/GuideRepository.java
  src/main/java/wazoo/service/GuideService.java
  src/main/java/wazoo/utils/S3Uploader.java
Labels: enhancement

#26 [Feature/wazoo 12] 가이드 매칭 api 리팩토링
  src/main/java/wazoo/controller/SearchController.java
  src/main/java/wazoo/dto/GuideDetailResponseDto.java
  src/main/java/wazoo/dto/SearchRequestDto.java
  src/main/java/wazoo/dto/SearchResponseDto.java
  src/main/java/wazoo/repository/GuideRepository.java
  src/main/java/wazoo/service/SearchService.java
Labels: enhancement, refactoring

#29 [Feature/wazoo-10] 가이드 리뷰 구현
  src/main/java/wazoo/controller/UserController.java
  src/main/java/wazoo/dto/CreateReviewRequestDto.java
  src/main/java/wazoo/dto/GuideReviewListResponseDto.java
  src/main/java/wazoo/dto/ReviewResponseDto.java
  src/main/java/wazoo/dto/UpdateReviewDto.java
  src/main/java/wazoo/dto/UserReviewListResponseDto.java
  src/main/java/wazoo/entity/Review.java
  src/main/java/wazoo/entity/ReviewSummary.java
  src/main/java/wazoo/repository/GuideRepository.java
  src/main/java/wazoo/repository/ReviewRepository.java
  src/main/java/wazoo/repository/ReviewSummaryRepository.java
  src/main/java/wazoo/service/UserService.java
Labels: enhancement

#32 [debug/wazoo-14] WAS 구축 관련 에러 해결
  Dockerfile
  src/main/java/wazoo/config/GoogleTranslationConfig.java
  src/main/java/wazoo/controller/UserController.java
  src/main/java/wazoo/repository/GuideRepository.java
Labels: bug, release

#35 [Feature/wazoo 17] 여행타입 관련 리팩토링
  src/main/java/wazoo/service/SearchService.java
  src/main/java/wazoo/service/SurveyService.java
  src/main/resources/questions.json
  src/main/resources/types.json
Labels: refactoring

#37 [feature/wazoo-16] 채팅 api 리팩토링
  src/main/java/wazoo/controller/ChatController.java
  src/main/java/wazoo/dto/ChatDto.java
  src/main/java/wazoo/dto/ChatListResponseDto.java
  src/main/java/wazoo/dto/MessageDTO.java
  src/main/java/wazoo/entity/Chat.java
  src/main/java/wazoo/entity/Message.java
  src/main/java/wazoo/repository/ChatRoomRepository.java
  src/main/java/wazoo/repository/GuideRepository.java
  src/main/java/wazoo/service/ChatRoomService.java
  src/main/java/wazoo/service/MessageService.java
Labels: refactoring

#40 [feature/wazoo-19] 회원 인증•인가 - JWT, 스프링 시큐리티 적용
  build.gradle
  src/main/java/wazoo/RoleType.java
  src/main/java/wazoo/config/AppConfig.java
  src/main/java/wazoo/config/PasswordEncoderConfig.java
  src/main/java/wazoo/config/SecurityConfig.java
  src/main/java/wazoo/controller/AuthApiController.java
  src/main/java/wazoo/controller/HomeController.java
  src/main/java/wazoo/controller/UserController.java
  src/main/java/wazoo/dto/CustomUserInfoDto.java
  src/main/java/wazoo/dto/ErrorResponseDto.java
  src/main/java/wazoo/dto/LoginRequestDto.java
  src/main/java/wazoo/dto/UserDto.java
  src/main/java/wazoo/dto/UserRegistrationDto.java
  src/main/java/wazoo/entity/User.java
  src/main/java/wazoo/repository/UserRepository.java
  src/main/java/wazoo/service/AuthService.java
  src/main/java/wazoo/service/AuthServiceImpl.java
  src/main/java/wazoo/service/ChatRoomService.java
  src/main/java/wazoo/service/CustomUserDetailsService.java
  src/main/java/wazoo/service/UserService.java
  src/main/java/wazoo/utils/CustomAccessDeniedHandler.java
  src/main/java/wazoo/utils/CustomAuthenticationEntryPoint.java
  src/main/java/wazoo/utils/CustomUserDetails.java
  src/main/java/wazoo/utils/JwtAuthFilter.java
  src/main/java/wazoo/utils/JwtUtil.java
Labels: enhancement, refactoring

#41 [feat] 마이페이지 조회 api 구현
  src/main/java/wazoo/controller/UserController.java
  src/main/java/wazoo/dto/MyPageResponseDto.java
  src/main/java/wazoo/service/UserService.java
Labels: enhancement
