Repository PICNIC-DEV/wazoo-backend, pull requests merged in 2024-07, with the labels that each got.

#5 Feature/wazoo 1
  .gitignore
  build.gradle
  src/main/java/wazoo/entity/ChatRoom.java
  src/main/java/wazoo/entity/Guide.java
  src/main/java/wazoo/entity/Message.java
  src/main/java/wazoo/entity/User.java
Labels: bug, enhancement

#10 [feature-6] 비속어 필터링 기능 구현
  src/main/java/wazoo/filtering/AhoCorasick.java
  src/main/java/wazoo/filtering/BadWordFiltering.java
  src/main/java/wazoo/filtering/TrieNode.java
  src/main/java/wazoo/utils/BadWordLoader.java
  src/main/resources/application.yml
  src/main/resources/badwords.txt
Labels: enhancement

#11 [Feature/wazoo-5] 유저 여행타입 생성
  build.gradle
  src/main/java/wazoo/config/SecurityConfig.java
  src/main/java/wazoo/controller/UserController.java
  src/main/java/wazoo/entity/User.java
  src/main/java/wazoo/repository/UserRepository.java
  src/main/java/wazoo/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/types.json
Labels: enhancement

#16 24.07.028
  .gitignore
  build.gradle
  src/main/java/wazoo/Application.java
  src/main/java/wazoo/config/GoogleTranslationConfig.java
  src/main/java/wazoo/config/OpenAIClient.java
  src/main/java/wazoo/config/OpenAIClientConfig.java
  src/main/java/wazoo/config/WebCorsConfig.java
  src/main/java/wazoo/config/WebSocketConfig.java
  src/main/java/wazoo/controller/ChatController.java
  src/main/java/wazoo/controller/GuideController.java
  src/main/java/wazoo/controller/TranslationController.java
  src/main/java/wazoo/controller/UserController.java
  src/main/java/wazoo/dto/ChatRoomDTO.java
  src/main/java/wazoo/dto/LoginRequestDto.java
  src/main/java/wazoo/dto/MessageDTO.java
  src/main/java/wazoo/dto/TranscriptionRequest.java
  src/main/java/wazoo/dto/UserDto.java
  src/main/java/wazoo/dto/UserRegistrationDto.java
  src/main/java/wazoo/dto/WhisperTranscriptionRequest.java
  src/main/java/wazoo/dto/WhisperTranscriptionResponse.java
  src/main/java/wazoo/entity/ChatRoom.java
  src/main/java/wazoo/entity/Guide.java
  src/main/java/wazoo/entity/Message.java
  src/main/java/wazoo/entity/User.java
  src/main/java/wazoo/filtering/AhoCorasick.java
  src/main/java/wazoo/filtering/BadWordFiltering.java
  src/main/java/wazoo/filtering/TrieNode.java
  src/main/java/wazoo/repository/ChatRoomRepository.java
  src/main/java/wazoo/repository/GuideRepository.java
  src/main/java/wazoo/repository/MessageRepository.java
  src/main/java/wazoo/repository/UserRepository.java
  src/main/java/wazoo/service/ChatRoomService.java
  src/main/java/wazoo/service/GuideService.java
  src/main/java/wazoo/service/MessageService.java
  src/main/java/wazoo/service/OpenAIClientService.java
  src/main/java/wazoo/service/TranslationService.java
  src/main/java/wazoo/service/UserService.java
  src/main/java/wazoo/utils/BadWordLoader.java
  src/main/resources/application.yml
  src/main/resources/badwords.txt
  src/main/resources/types.json
Labels: release
